apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-echo26c6ab0d-3686-457d-9b88-a24199ae7d46.fullname" . }}-config
  labels:
    {{- include "go-echo26c6ab0d-3686-457d-9b88-a24199ae7d46.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.envVars }}
  {{ $key }}: {{ $value }}
{{- end }}
