apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-echo9f6996c0-baa4-4d13-aa25-5e955ea2a65d.fullname" . }}-config
  labels:
    {{- include "go-echo9f6996c0-baa4-4d13-aa25-5e955ea2a65d.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.envVars }}
  {{ $key }}: {{ $value }}
{{- end }}
