apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-echo56d09dbc-f7ec-48a6-a3f9-793d88a5d240.fullname" . }}-config
  labels:
    {{- include "go-echo56d09dbc-f7ec-48a6-a3f9-793d88a5d240.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.envVars }}
  {{ $key }}: {{ $value }}
{{- end }}
