apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-echo4edc1001-e2de-4a54-827a-01fcdcc63c63.fullname" . }}
  labels:
    {{- include "go-echo4edc1001-e2de-4a54-827a-01fcdcc63c63.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "go-echo4edc1001-e2de-4a54-827a-01fcdcc63c63.selectorLabels" . | nindent 6 }}
