apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-echo080358fa-13a9-45c7-baa7-d0a8c45ae4a9.fullname" . }}
  labels:
    {{- include "go-echo080358fa-13a9-45c7-baa7-d0a8c45ae4a9.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "go-echo080358fa-13a9-45c7-baa7-d0a8c45ae4a9.selectorLabels" . | nindent 6 }}
