apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-echoace587d1-0cf1-457d-850d-6cff8ed82a05.fullname" . }}
  labels:
    {{- include "go-echoace587d1-0cf1-457d-850d-6cff8ed82a05.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "go-echoace587d1-0cf1-457d-850d-6cff8ed82a05.selectorLabels" . | nindent 6 }}
