apiVersion: v1
kind: ConfigMap
metadata:
  name: go-echo-config
  namespace: devhub-pvt-cluster-e2e-test-id-9
  labels:
    app.kubernetes.io/name: go-echo
    kubernetes.azure.com/generator: devhub
data: